
# +------------------------------------------------------------------------------------------------------------------------------------+
# | (C) Copyright Kyndryl Solutions Ltd. 2024                                                                                          |
# | All Rights Reserved                                                                                                                |
# +------------------------------------------------------------------------------------------------------------------------------------+
# | Program: Examples of using become : 1.0.0                                                                                          |
# | Original Author: Rushabh S.(rushabhchandrashekharsawarka@kyndryl.com)    Last Update: 8/May/2024                                              |
# | Edit By: Nihar Behera (niharranjanbehera@kyndryl.com)              Last update: 8/May/2024                                              |
# |                                                                                                                                    |
# +------------------------------------------------------------------------------------------------------------------------------------+
# |                                                                                                                                    |
# | Description:                                                                                                                       |
# |                                                                                                                                    |
# | Ansible playbook will gatehr the nfs mount data.                                                                                   |
# |  Variables used:                                                                                                                   |
# |   - IP_LIST                                                                                                                        |
# |   - delegate_server: server where report gets generated (default: localhost)                                                       |
# |                                                                                                                                    |
# | Prerequisites:                                                                                                                     |
# |   - Nfs mount point should be present                                                                                              |                                 
# +------------------------------------------------------------------------------------------------------------------------------------+
# |                                                                                                                                    |
# | Change Log:                                                                                                                        |
# |   - 1.0   Script created and approved   (PD -    /  /2025)                                                                         |
# +------------------------------------------------------------------------------------------------------------------------------------+
# We are using vilipat1 user for file copy, file transfer in our environment since data is sensetive and account has not autorized to transfer data to SFS. So data is stored locally.
- name: Colortoken Log purge
  hosts: "{{ IP_LIST |lower }}"
  gather_facts: false
  ignore_errors: true
  become: true
  tasks:
  
   - name: date
     shell: date +%d%m%y
     register: dt
     run_once: true

   - name: Runnning commands
     shell: |
        if [ -d /etc/colortokens ]; then
            DIR="/etc/colortokens"
            THRESHOLD=$((1024 * 1024))  # 1GB in KB
        
            DIR_SIZE=$(du -sk "$DIR" | awk '{print $1}')
        
            if [ "$DIR_SIZE" -gt "$THRESHOLD" ]; then
                echo "[$(date)] Size of $DIR exceeds 1GB. Deleting old 'channels*' files..."
                find "$DIR" -name 'channels*' -type f -mtime +15 -exec rm -f {} \;
            fi
        
            DIR_SIZE1=$(du -sk "$DIR" | awk '{print $1}')
            echo "$(uname -n),$(uname),$DIR_SIZE,$DIR_SIZE1" > /tmp/colortokens.log
        else
            echo "$(uname -n),$(uname),/etc/colortokens dir not available" > /tmp/colortokens.log
        fi
     register: out
     async: 600
     poll: 20
     environment: 
         PATH: "/sbin:/usr/sbin:/usr/bin:/bin:/usr/lpp/mmfs/bin"


   - name: cat file for output
     shell: cat /tmp/colortokens.log
     register: out1

   - name: Insert header line only if not present
     lineinfile:
      path: /ansivar/cacf/Job_{{ tower_job_id }}_colortoken_purge_size_{{ dt.stdout }}.csv
      line: "IP,Ansible_Hostname,Server_Hostname,OS_Name,Before_Size_KB,After_Size_KB"
      insertafter: BOF
      create: yes
      state: present
     run_once: true
     delegate_to: ndc3clnpans01
    
   # - name: header
   #   shell: echo IP,Ansible_Hostname,Server_Hostname,OS_Name,Before_Size_KB,After_Size_KB >> /ansivar/cacf/Job_{{ tower_job_id }}_colortoken_purge_size_{{ dt.stdout }}.csv
   #   run_once: true
   #   delegate_to: ndc3clnpans01

   # - name: store output
   #   shell: echo {{hostvars[inventory_hostname]['ansible_host']}},{{ inventory_hostname }},{{ out1.stdout }} >> /ansivar/cacf/Job_{{ tower_job_id }}_colortoken_purge_size_{{ dt.stdout }}.csv
   #   delegate_to: ndc3clnpans01
     
   - name: Insert header line only if not present
     lineinfile:
      path: /ansivar/cacf/Job_{{ tower_job_id }}_colortoken_purge_size_{{ dt.stdout }}.csv
      line: "{{hostvars[inventory_hostname]['ansible_host']}},{{ inventory_hostname }},{{ out1.stdout }} "
      insertafter: EOF
      create: yes
      state: present
     delegate_to: ndc3clnpans01     
     
   # - debug: 
   #    msg: Download Artifacts from link "http://10.94.77.236:8085/setup/cacf/nfs_data/NFS_DATA_{{ dt.stdout }}.csv"
   #   run_once: true


   - name: Sent the mail to user
     mail:
         host: 10.94.147.12
         port: 25
         to: chandanvirchand.pandit@kyndryl.com
         cc: rushabhchandrashekharsawarka@kyndryl.com
         subject: Colortokens Post Purging Size
         body: |
             Hello Team, 
             PFA of /etc/colortokens dir purging data
           
             Regards,
             Automation Team 
         from: ansible_automation@vodafoneidea.com
         attach: 
           - "/ansivar/cacf/Job_{{ tower_job_id }}_colortoken_purge_size_{{ dt.stdout }}.csv"
     run_once: true 
     delegate_to: ndc3clnpans01
     become: true
     ignore_errors: yes     
